name: AsyncWorldEdit-TitleManager
main: org.primesoft.asyncworldedit.progressDisplay.TitleManagerBackend
version: ${global.awe.version}
api-version: 1.13
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin provides TitleManager progress display backend for AsyncWorldEdit
authors: [SBPrime]
depend: [TitleManager]