name: AsyncWorldEdit-BountifulAPI
main: org.primesoft.asyncworldedit.progressDisplay.BountifulAPIBackend
version: ${global.awe.version}
api-version: 1.13
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin provides BountifulAPI progress display backend for AsyncWorldEdit
authors: [SBPrime]
depend: [BountifulAPI]

